Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -16,9 +16,9 @@ jobs:
 
     - name: Validate Files Exist
       run: |
-        test -f DevOps-Project/Dummy-portfolio-code/index.html || (echo "index.html missing" && exit 1)
-        test -f DevOps-Project/Dummy-portfolio-code/style.css || (echo "style.css missing" && exit 1)
-        test -f DevOps-Project/Dummy-portfolio-code/script.js || (echo "script.js missing" && exit 1)
+        test -f index.html || (echo "index.html missing" && exit 1)
+        test -f style.css || (echo "style.css missing" && exit 1)
+        test -f script.js || (echo "script.js missing" && exit 1)
 
     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v2
@@ -29,6 +29,6 @@ jobs:
 
     - name: Deploy to S3
       run: |
-        aws s3 sync DevOps-Project/Dummy-portfolio-code/ s3://${{ secrets.AWS_S3_BUCKET_NAME }} --delete
+        aws s3 sync . s3://${{ secrets.AWS_S3_BUCKET_NAME }} --delete
 
 ```
