Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -16,19 +16,19 @@ jobs:
 
     - name: Validate Files Exist
       run: |
-        test -f index.html || (echo "index.html missing" && exit 1)
-        test -f style.css || (echo "style.css missing" && exit 1)
-        test -f script.js || (echo "script.js missing" && exit 1)
+        test -f DevOps-Project/Dummy-portfolio-code/index.html || (echo "index.html missing" && exit 1)
+        test -f DevOps-Project/Dummy-portfolio-code/style.css || (echo "style.css missing" && exit 1)
+        test -f DevOps-Project/Dummy-portfolio-code/script.js || (echo "script.js missing" && exit 1)
 
     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v2
       with:
-        aws-access-key-id: ${{ secrets.AKIAWX6GPYXF7NNFQLVD }}
-        aws-secret-access-key: ${{ secrets.iNBTonA8gs+S6SeyMjzgzrpx8ilU4P1Dwj71deiQ }}
+        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: 'ap-south-1'
 
     - name: Deploy to S3
       run: |
-        aws s3 sync s3://${{ secrets.devops-cicdproject }} --delete
+        aws s3 sync DevOps-Project/Dummy-portfolio-code/ s3://${{ secrets.AWS_S3_BUCKET_NAME }} --delete
 
 ```
